package vistas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author DAVID
 */
public class Main extends javax.swing.JFrame {

    String usuario;

    public Main() {
        initComponents();
        //recuperar nombre de usuario del login
        usuario = Login.username;
        
        //fijar tamanio fijo
        setSize(530, 400);
        setResizable(false);

        //titulo
        setTitle("Teachtools - Sesion de " + usuario);
        setLocationRelativeTo(null);

        //evitar que el programa se sigua ejecutando en 2do plano
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        //fondo imagen
        ImageIcon fondo = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg"); // src/paquete/nombreImagen
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_bgfondo.getWidth(),
                jLabel_bgfondo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_bgfondo.setIcon(icono);
        this.repaint();

        jLabel_saludo.setText("Bienvenido(a) " + usuario);
    }

    //metodo override llamado para cambiar icono de interfaz
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo2.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_saludo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_alumnos = new javax.swing.JButton();
        btn_materias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_bgfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_saludo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel_saludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_saludo.setText("Bienvenido Usuario");
        getContentPane().add(jLabel_saludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 530, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("© 2020 TecnoFast Enterprise");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 530, -1));

        btn_alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno.png"))); // NOI18N
        btn_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alumnosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 145, 145));

        btn_materias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/materia.png"))); // NOI18N
        btn_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_materiasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 145, 145));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("ALUMNOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("REGISTRAR MATERIAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));
        getContentPane().add(jLabel_bgfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_materiasActionPerformed
        Materias registro = new Materias();
        registro.setVisible(true);
    }//GEN-LAST:event_btn_materiasActionPerformed

    private void btn_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alumnosActionPerformed
        Alumnos acceso = new Alumnos();
        acceso.setVisible(true);
    }//GEN-LAST:event_btn_alumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alumnos;
    private javax.swing.JButton btn_materias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_bgfondo;
    private javax.swing.JLabel jLabel_saludo;
    // End of variables declaration//GEN-END:variables
}
